image:
  name: "python:3.11-alpine"
  entrypoint: ["/bin/sh", "-c"]

stages:
  - test
  - build
  - push

test:
  stage: test
  image: python:latest
  before_script:
    # Optional: Install any dependencies before running the script
    - apt-get update && apt-get install -y python3-pip
  script:
    - pip install -r gateway/requirements.txt
    - pip install fastapi pytest httpx
    - cd gatway/ # Change this to the correct path if needed
    - python3 -m pytest

build:
  stage: build
  script:
    # Build the container image
    - docker build -t assma123/k-api-gateway:latest -f gateway/Dockerfile gateway
    # List the container images
    - docker image ls

push:
  stage: push
  script:
    # Push the container image to DockerHub
    - docker push assma123/k-api-gateway:latest
    # List the container images
    - docker image ls
