image:
  name: "python:3.11-alpine"
  entrypoint: ["/bin/sh", "-c"]

stages:
  - test
  - build
  - push

test:
  stage: test
  image: python:latest
  before_script:
# Show docker daemon info (optional, good for debugging)
# - docker login registry.gitlab.com
- sudo apt install python3-pip -y
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip install fastapi
    - pip install pytest
    - pip install httpx
    - pip install jinja2
    #- cd gateway/
    - python3 -m pytest


build:
  stage: build
  script:
    # Build the container image
    - docker build -t assma123/k-api-gateway:latest -f gateway/Dockerfile gateway
    # List the container images
    - docker image ls

push:
  stage: push
  script:
    # Push the container image to DockerHub
    - docker push assma123/k-api-gateway:latest
    # List the container images
    - docker image ls
