image:
  name: "python:3.11-alpine"
  entrypoint: ["/bin/sh", "-c"]

stages:
  - test
  - build
  - push

test:
  stage: test
  image: python:latest
  before_script:
    # Afficher les informations du démon Docker (optionnel, utile pour le débogage)
    # - docker login registry.gitlab.com
    - apt-get update && apt-get install -y python3-pip
  script:
    - pip install fastapi
    - pip install pytest
    - pip install httpx
    - pip install jinja2
    # - cd gateway/ # Décommentez cette ligne si nécessaire pour naviguer dans le bon dossier
    #- python3 -m pytest


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # Build the container image
    - docker build -t assma123/k-api-gateway:latest -f gateway/Dockerfile gateway
    # List the container images
    - docker image ls

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    # Se connecte à DockerHub avec les identifiants (username et token) configurés dans les variables CI/CD
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Pousse l'image sur DockerHub
    - docker push assma123/k-api-gateway:latest
