# service-gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 8001          # Port exposé par le service
      targetPort: 8000    # Port sur lequel l'application écoute dans le conteneur
      protocol: TCP
  selector:
    app: gateway
