# deployment-gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: assma123/k-api-gateway:latest
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: gateway-volume
              mountPath: /app
      volumes:
        - name: gateway-volume
          hostPath:
            path: /home/ubuntu/gitlab_exam/gateway
            type: Directory
