# service-orders.yaml
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: NodePort
  externalTrafficPolicy: Local  # Changez de Cluster à Local
  ports:
    - port: 8001          # Port exposé par le service
      targetPort: 8001    # Port sur lequel l'application écoute dans le conteneur
      protocol: TCP
  selector:
    app: orders
