# deployment-users.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: gateway
          image: assma123/k-users:latest
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: users-volume
              mountPath: /app
      volumes:
        - name: users-volume
          hostPath:
            path: /home/ubuntu/gitlab_exam/users
            type: Directory

